# Site settings
title: Блог 101 обезьяны
email: varlamoved@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://io.varlamoved.ru" # the base hostname & protocol for your site
twitter_username: varlamoved
github_username:  varlamoved

# Build settings
markdown: kramdown
