# Site settings
title: varlamoved
email: varlamoved@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://io.varlamoved.ru" # the base hostname & protocol for your site
twitter_username: varlamoved
github_username:  varlamoved
skype: varlamoved


# Build settings
markdown: kramdown
